# Generated by Django 4.1.3 on 2022-12-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_status_todoitems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='Description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
