# Generated by Django 4.1.3 on 2022-12-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
