# Generated by Django 4.1.3 on 2022-12-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='status',
            field=models.IntegerField(choices=[(0, 'NotStarted'), (1, 'OnGoing'), (2, 'Completed')], default=0),
        ),
    ]
